title = "buzzer-beater"

[owner]
name = "Aaron Di Silvestro"
email = "aaron.disilvestro@nike.com"

[application]
name = "buzzer-beater"
secret = "c8a5b315002bd4db32630a8ba3b70d10cd4f74ab"
salt = "d8dcb36de1087e98fcf18bde2eb0316c53ca1e66"

[database]
name = "door.db"
buckets = ["User", "Message"]
